DockYard/ember-composable-helpers

- LICENSE.md
- README.md
- addon/helpers/pipe.js
- addon/index.js
- app/helpers/pipe.js
- tests/acceptance/pipe-test.js
- tests/dummy/app/controllers/pipe.js
- tests/dummy/app/router.js
- tests/dummy/app/templates/components/convoluted-add.hbs
- tests/dummy/app/templates/compose.hbs
- tests/dummy/app/templates/pipe.hbs
- tests/unit/helpers/pipe-test.js
Taken from https://github.com/rtablada/ember-compose-action-helper
> Pipe helper

- README.md
- addon/helpers/repeat.js
- addon/index.js
- app/helpers/repeat.js
- tests/integration/helpers/repeat-test.js
- tests/unit/helpers/repeat-test.js
> Add Repeat helper

- README.md
- addon/helpers/range.js
- addon/index.js
- addon/utils/comparison.js
- app/helpers/range.js
- tests/integration/helpers/range-test.js
- tests/unit/helpers/range-test.js
> Add Range helper

- addon/helpers/range.js
- addon/helpers/repeat.js
- tests/unit/helpers/repeat-test.js
> Fix Repeat helper

- README.md
- addon/helpers/dec.js
- addon/helpers/inc.js
- addon/index.js
- app/helpers/dec.js
- app/helpers/inc.js
- tests/integration/helpers/dec-test.js
- tests/integration/helpers/inc-test.js
- tests/unit/helpers/dec-test.js
- tests/unit/helpers/inc-test.js
> Simple Math helpers

- README.md
- addon/helpers/join.js
- app/helpers/join.js
- tests/integration/helpers/join-test.js
> Add {{join}} helper

- README.md
- addon/helpers/w.js
- addon/index.js
- app/helpers/w.js
- tests/integration/helpers/w-test.js
> Add {{w}} helper

- README.md
- addon/helpers/intersect.js
- addon/helpers/union.js
- addon/index.js
- app/helpers/intersect.js
- app/helpers/union.js
- tests/integration/helpers/intersect-test.js
- tests/integration/helpers/union-test.js
> Add {{intersect}} and {{union}} helper

- .travis.yml
- README.md
- index.js
- lib/difference.js
- lib/intersection.js
- package.json
- test/index-test.js
- test/lib/difference-test.js
- test/lib/intersection-test.js
> Tree shake helpers using `only` or `except`

- test/index-test.js
> Add unit test to index

- README.md
I think this is what the intent was
> Fix `w` helper in README

- README.md
- addon/helpers/contains.js
- addon/index.js
- app/helpers/contains.js
- tests/integration/helpers/contains-test.js
- tests/unit/helpers/contains-test.js
> Implement Contains helper

- README.md
- addon/helpers/dec.js
- addon/helpers/drop.js
- addon/helpers/filter-by.js
- addon/helpers/group-by.js
- addon/helpers/inc.js
- addon/helpers/join.js
- addon/helpers/map-by.js
- addon/helpers/sort-by.js
- addon/helpers/take.js
- addon/helpers/toggle.js
- tests/integration/helpers/dec-test.js
- tests/integration/helpers/drop-test.js
- tests/integration/helpers/filter-by-test.js
- tests/integration/helpers/group-by-test.js
- tests/integration/helpers/inc-test.js
- tests/integration/helpers/join-test.js
- tests/integration/helpers/map-by-test.js
- tests/integration/helpers/sort-by-test.js
- tests/integration/helpers/take-test.js
- tests/integration/helpers/toggle-test.js
- tests/unit/helpers/dec-test.js
- tests/unit/helpers/toggle-test.js
> Switch to subject last

- addon/helpers/pipe.js
- tests/unit/helpers/pipe-test.js
> Fix return value passing in `pipe` helper

- addon/helpers/pipe.js
- tests/unit/helpers/pipe-test.js
See https://github.com/DockYard/ember-composable-helpers/pull/78#discussion_r53863325
> Fix undefined leaking through pipe

- README.md
- addon/helpers/dasherize.js
- addon/index.js
- app/helpers/dasherize.js
- tests/integration/helpers/dasherize-test.js
This PR adds the `dasherize` helper per the issue here
Closes #66
> Add dasherize helper

- README.md
- addon/helpers/underscore.js
- addon/index.js
- app/helpers/underscore.js
- tests/integration/helpers/underscore-test.js
This PR adds the `underscore` helper per issue https://github.com/DockYard/ember-composable-helpers/issues/69
> Add string underscore helper

- README.md
- addon/helpers/camelize.js
- addon/index.js
- app/helpers/camelize.js
- tests/integration/helpers/camelize-test.js
Adds the `camelize` helper per issue
Closes #68
> Add camelize helper

- README.md
- addon/helpers/classify.js
- addon/index.js
- app/helpers/classify.js
- tests/integration/helpers/classify-test.js
The PR adds a `classify` helper per issue https://github.com/DockYard/ember-composable-helpers/issues/67
> Add classify helper

- README.md
- addon/helpers/pipe.js
- addon/utils/is-promise.js
- tests/integration/helpers/pipe-test.js
- tests/unit/helpers/pipe-test.js
- tests/unit/utils/is-promise-test.js
> Make `pipe` helper promise aware

- README.md
- addon/helpers/reverse.js
- app/helpers/reverse.js
- tests/integration/helpers/reverse-test.js
For: https://github.com/DockYard/ember-composable-helpers/issues/19
> Add a Reverse Helper

- README.md
- addon/helpers/chunk.js
- addon/index.js
- app/helpers/chunk.js
- tests/integration/helpers/chunk-test.js
- tests/unit/helpers/chunk-test.js
Adds chunk helper (Issue https://github.com/DockYard/ember-composable-helpers/issues/57)
> Add chunk helper

- README.md
- addon/-private/create-needle-haystack-helper.js
- addon/helpers/without.js
- addon/index.js
- app/helpers/without.js
- tests/integration/helpers/without-test.js
- tests/unit/helpers/without-test.js
> Add `Without` helper

- addon/helpers/sort-by.js
- tests/integration/helpers/sort-by-test.js
> Allows a sort array/function to be passed in to {{sort-by}}

- README.md
- addon/helpers/truncate.js
- addon/index.js
- app/helpers/truncate.js
- tests/integration/helpers/truncate-test.js
```handlebars
{{truncate "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas hendrerit quam enim, in suscipit est rutrum id. Etiam vitae blandit purus, sed semper sem." 140}}
```
returns
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas hendrerit quam enim, in suscipit est rutrum id. Etiam vitae blandit purus,...
```
> Add truncate helper

- addon/helpers/array.js
- app/helpers/array.js
- tests/integration/helpers/array-test.js
- tests/unit/helpers/array-test.js
closes #142 
Signed-off-by: Taras Mankovski <taras@embersherpa.com>
> adds array helper and tests

- README.md
- addon/helpers/shuffle.js
- addon/index.js
- app/helpers/shuffle.js
- tests/integration/helpers/shuffle-test.js
> Added shuffle helper

- addon/helpers/chunk.js
- tests/unit/helpers/chunk-test.js
> Allow chunk helper to work with CP length.

- tests/integration/helpers/map-by-test.js
Wrote this test to validate an experiment, thought I might as well PR it.
> Add a test case to map-by

- addon/helpers/contains.js
- addon/helpers/shuffle.js
- addon/helpers/without.js
> Use Ember.get to get length from arrays

- README.md
- addon/helpers/flatten.js
- addon/index.js
- app/helpers/flatten.js
- tests/integration/helpers/flatten-test.js
- tests/unit/helpers/flatten-test.js
Integration tests and documentation taken from https://github.com/DockYard/ember-composable-helpers/pull/96
> flatten helper

- README.md
- addon/helpers/shuffle.js
- tests/integration/helpers/shuffle-test.js
> Fix argument ordering of shuffle

- README.md
- addon/helpers/optional.js
- addon/index.js
- app/helpers/optional.js
- tests/integration/helpers/optional-test.js
> Add the {{optional}} helper

- README.md
- addon/helpers/toggle.js
- tests/integration/helpers/toggle-test.js
> Add optional args to the toggle helper

- .travis.yml
- addon/-private/create-multi-array-helper.js
- addon/helpers/append.js
- addon/helpers/flatten.js
- bower.json
- config/ember-try.js
- package.json
- tests/helpers/module-for-acceptance.js
Also had to fix jshint errors.
> Update ember-cli to 2.6.0

- README.md
- addon/helpers/slice.js
- addon/index.js
- app/helpers/slice.js
- tests/integration/helpers/slice-test.js
Supercedes #160
Resolves merge conflicts and does a little bit of cleanup.
> Slice helper

- README.md
- addon/helpers/sort-by.js
- tests/integration/helpers/sort-by-test.js
Rebased version with minor tweaks from #151
> Fixes {{sort-by}} with a function

- addon/helpers/without.js
- tests/integration/helpers/without-test.js
> Fix without with Ember Arrays

- addon/helpers/find-by.js
- tests/integration/helpers/find-by-test.js
Supercedes #192 with a linting fix
> [BUGFIX] {{filter-by}} must work without prototype extensions

- README.md
- addon/helpers/titleize.js
- addon/index.js
- addon/utils/titleize.js
- app/helpers/titleize.js
- app/utils/titleize.js
- tests/integration/helpers/titleize-test.js
- tests/unit/utils/titleize-test.js
Supercedes #161 with a rebase and minor enhancements
> Titleize Helper

- README.md
- addon/-private/create-needle-haystack-helper.js
- addon/helpers/has-next.js
- addon/helpers/has-previous.js
- addon/helpers/next.js
- addon/helpers/previous.js
- addon/index.js
- addon/utils/get-index.js
- addon/utils/is-equal.js
- app/helpers/has-next.js
- app/helpers/has-previous.js
- app/helpers/next.js
- app/helpers/previous.js
- tests/integration/helpers/has-next-test.js
- tests/integration/helpers/has-previous-test.js
- tests/integration/helpers/next-test.js
- tests/integration/helpers/previous-test.js
- tests/unit/helpers/next-test.js
- tests/unit/helpers/previous-test.js
- tests/unit/utils/get-index-test.js
- tests/unit/utils/is-equal-test.js
* Includes `hasNext` and `hasPrevious`
* Adds `addIndex` and `isEqual` util
Closes #62
> Add next and previous helpers

- config/ember-try.js
- package.json
Stop testing all the versions.
Now only tests:
> Update Ember Try scenarios

- .travis.yml
- circle.yml
> Make sure node-tests run in CI

- .editorconfig
- .jshintrc
- addon/-private/closure-action.js
- addon/helpers/contains.js
- addon/helpers/group-by.js
- addon/helpers/without.js
- addon/utils/get-index.js
- addon/utils/includes.js
- bower.json
- package.json
- tests/.jshintrc
- tests/dummy/app/app.js
- tests/dummy/app/index.html
- tests/dummy/app/router.js
- tests/dummy/config/environment.js
- tests/helpers/destroy-app.js
- tests/helpers/start-app.js
- tests/index.html
- tests/unit/helpers/chunk-test.js
- tests/unit/helpers/invoke-test.js
Notes:
- Bumped `ember-exam` to `v0.4.6` for [this change](https://github.com/trentmwillis/ember-exam/commit/667363ff792acb2770d3c8b48bb14188d8cc9526)
- Bumped `ember-suave` to `v4.0.0` for [this change](https://github.com/DockYard/ember-suave/commit/7ac090da21141837776aefb99fd8504e5c9c5648)
> Upgrade Ember CLI to 2.7.0 + Suave'd

- addon/helpers/titleize.js
- tests/integration/helpers/titleize-test.js
> Fixes titleize properly handling null

- README.md
> Document the {{queue}} helper

- README.md
Thought it went well with this, and truth helpers were already mentioned
> Add ember-math-helpers link

- addon/helpers/dec.js
- addon/helpers/inc.js
- tests/unit/helpers/dec-test.js
- tests/unit/helpers/inc-test.js
The goal of PR #174 was to parse string values to number, but it only handles integer case. This PR is to enhance it by allowing any number, not just integers.
> Allow inc/dec to take float

- README.md
> Fix pipe readme example

- index.js
> Check if whitelist|blacklist exists in filterHelpers

- index.js
> Fix filter helper regexp

- addon/helpers/range.js
- tests/integration/helpers/range-test.js
> Fixed range helper inclusive, when args are the same value

- addon/helpers/drop.js
- addon/helpers/filter-by.js
- addon/helpers/filter.js
- addon/helpers/find-by.js
- addon/helpers/group-by.js
- addon/helpers/has-next.js
- addon/helpers/has-previous.js
- addon/helpers/join.js
- addon/helpers/map-by.js
- addon/helpers/map.js
- addon/helpers/object-at.js
- addon/helpers/reduce.js
- addon/helpers/reject-by.js
- addon/helpers/reverse.js
- addon/helpers/shuffle.js
- addon/helpers/slice.js
- addon/helpers/take.js
This restores some of the helper functions exports that were removed during #321
> Restore helper functions exports

- addon/helpers/map-by.js
- tests/integration/helpers/map-by-test.js
> bugfix map-by with ember-data models

- tests/unit/helpers/pipe-test.js
- tests/unit/helpers/queue-test.js
Closes # .
replaces the deprecated `sinon.sandbox.create` with `sinon.createSandbox`
> replace deprecated method sinon sandbox

- addon/helpers/sort-by.js
- tests/integration/helpers/entries-test.js
- tests/integration/helpers/sort-by-test.js
> Refactor sort-by with native implementation of sort

- README.md
- addon/helpers/call.js
- app/helpers/call.js
- tests/integration/helpers/call-test.js
> Add call helper

- addon/helpers/sort-by.js
- tests/integration/helpers/sort-by-test.js
Fixes https://github.com/DockYard/ember-composable-helpers/issues/385
/cc @snewcomer
> `{{sory-by}}` - Don't sort array when key is empty

- addon/helpers/sort-by.js
close #418 
Before | After
--|--
@cibernox @jleja
> Fix slow sort-by
