DockYard/ember-composable-helpers

README.md, addon/helpers/compact.js, addon/index.js, app/helpers/compact.js, tests/integration/helpers/compact-test.js
For: https://github.com/DockYard/ember-composable-helpers/issues/56
I thought I'd take a stab at this one — but, the requirement to compact objects leaves me a bit flummoxed. Per the [`each-in` helper](https://github.com/emberjs/ember.js/blob/v2.3.0/packages/ember-htmlbars/lib/helpers/each-in.js#L8), it's "unbound, in that new (or removed) properties added to the target object will not be rendered". 
So even though this compact helper would be dynamically adding/removing keys, the `each-in` helper would never update to render the new/removed keys. 
This PR does not attempt to address compacting based on object values yet — can add that if, even given the constraints, y'all would like to have that added. :)
=> Add Compact Helper

README.md
Update example to match changes resulting from https://github.com/DockYard/ember-composable-helpers/issues/54
=> Fix argument order in `map-by` example

addon/utils/is-promise.js, tests/unit/utils/is-promise-test.js
- Relaxed the `instanceof` check to duck type if the object implements
Promise-like methods to work with Objects that include the
PromiseProxy mixin
Closes #102
=> Make `pipe` work with PromiseProxies

addon/helpers/filter-by.js, addon/helpers/reject-by.js
We were running in to an issue where we were trying to filter-by a property that holds a value of `false`
eg:
```js
{{#each (filter-by "active" false users) as |user|}}
{{user.name}} is not active.
{{/each}}
```
In this case the helper checks the value which will always return false and then default to the presence check.
=> check for value presence rather than value

tests/integration/helpers/filter-by-test.js
Was already fixed in #112.
Closes #88, #98
=> Add test for filter-by recompute on false values

README.md, addon/helpers/invoke.js, addon/index.js, app/helpers/invoke.js, tests/integration/helpers/invoke-test.js, tests/unit/helpers/invoke-test.js
The main motivation of this helper is to write code like
```handlebars
<a {{action (invoke 'save' model)}}>Save</a>
<a {{action (invoke 'rollbackAttributes' model)}}>Undo</a>
```
against Ember Data models. It avoids boiler plate actions that only call on methods.
As it is intended for use with Ember Data like objects or collections, if the subject of this action is an Array the method gets called on every member of the array. Also, as in the case of 'save()' method above, if the function returns a Promise on the object or on its members (as in the array case) the helper will be aware of that. This way this becomes possible: 
```handlebars
{{#each people as |person|}}
<p>
{{input value=person.name}} <a {{action (invoke 'rollbackAttributes' person)}}>Undo</a>
<span …
```
=> add invoke helper

README.md
In the example for `pipe-action`
=> Updated README to include missing closing parens

README.md
Updates `filter-by` documentation in README to reference the correct argument that's passed in as a value.
=> Updates `filter-by` documentation in README.

addon/helpers/find-by.js, tests/integration/helpers/find-by-test.js
At the moment `{{filter-by 'name' userName users}}` do not update if `userName` is updated.
=> [BUGFIX] {{filter-by}} must also observe changes in the value

README.md, addon/helpers/object-at.js, addon/index.js, app/helpers/object-at.js, tests/integration/helpers/object-at-test.js
The goal of this helper was to facilitate pagination in conjunction with the `chunk` helper. You can get similar results with Ember's `get` helper, but it requires the index to be a string, as far as I can tell.
=> Implementing object-at helper.

addon/-private/create-multi-array-helper.js, addon/helpers/append.js, addon/helpers/chunk.js, addon/helpers/compact.js, addon/helpers/contains.js, addon/helpers/filter-by.js, addon/helpers/flatten.js, addon/helpers/group-by.js, addon/helpers/join.js, addon/helpers/object-at.js, addon/helpers/reject-by.js, addon/helpers/reverse.js, addon/helpers/shuffle.js, addon/helpers/sort-by.js, addon/helpers/without.js
There were three different syntaxes being used:
```js
import { typeOf } from 'ember-utils';
typeOf(array) !== 'array';
```
```js
import { isEmberArray as isArray } from 'ember-array/utils';
isArray(array);
```
```js
import { isEmberArray } from 'ember-array/utils';
isEmberArray(array);
```
This standardizes to use the third syntax across all helpers.
=> standardize array checks to Ember arrays (#197)

README.md, addon/helpers/html-safe.js, app/helpers/html-safe.js, tests/integration/helpers/html-safe-test.js
Add support for Ember.String.htmlSafe. 
Usage: 
```hbs
<button class={{html-safe (join '  ' myClasses)}}>Custom Button</button>
```
=> html-safe helper

addon/helpers/queue.js, addon/index.js, app/helpers/queue.js, tests/integration/helpers/queue-test.js, tests/unit/helpers/queue-test.js
Supercedes #134
Similar to the pipe helper, but instead of chaining return values into
arguments, this will pass the same arguments to all actions.
=> Add queue helper

addon/-private/closure-action.js, addon/helpers/array.js, addon/helpers/pipe-action.js, addon/helpers/sort-by.js, addon/helpers/toggle-action.js
* Avoid mutating params/hash in helpers.
* Prevent errors when `ACTION` isn't needed.
=> Make compatible with Ember 2.9.0-beta.2+.

addon/helpers/filter-by.js, addon/helpers/reject-by.js, addon/utils/is-equal.js, tests/integration/helpers/filter-by-test.js, tests/integration/helpers/reject-by-test.js, tests/unit/utils/is-equal-test.js
This PR modifies `utils/isEqual` to use `Ember.isEqual`. `Ember.isEqual` only checks if the first argument implements `isEqual` interface, so I have to check twice: first for second argument against first, followed by first argument against second.
Closes #235
=> Use Ember.isEqual

addon/helpers/filter-by.js, addon/helpers/reject-by.js, tests/integration/helpers/filter-by-test.js, tests/integration/helpers/reject-by-test.js
Addressing #98. It was closed but has not been fixed.
According to documentation:
- `filter-by`: `If you omit the second argument it will test if the property is truthy.`
- `reject-by`: `If you omit the third argument it will test if the property is falsey.`
Currently the checks are done using `Ember.isPresent()` and `Ember.isEmpty()` which don't really test truthiness and falsiness. For example, `Ember.isPresent(false)` returns `true` which is not the desired result.
I added failing tests for some falsy values (`false`, `0`, `''` and `NaN`) and one truthy value (`[]`), and changed the implementation to using plain JavaScript boolean operators.
Also the word `third` seems incorrect so I changed it to `second`.
=> Fix truthy/falsy checks in filter-by and reject-by when value is omitted

addon/helpers/group-by.js, tests/integration/helpers/group-by-test.js
1.1.1
See [this Twiddle](https://ember-twiddle.com/9357cee3702bea9893c18ad5003240b3?openFiles=routes.index.js%2C) for a broken use-case.
See Twiddle above. Add/remove period `.` from `supplierName` attribute of one of the contract objects in the `index` route.
The supplierName should appear as a string in the template.
If the supplierName contains a period, it cannot be set as a key. Ember Composable Helpers throws Ember Error: `Error: Property set failed: You passed an empty path`
---
In `ember-composable-helpers/addon/helpers/group-by.js`, changing the following...
```
if (!isEmberArray(group)) {
group = emberArray();
set(groups, groupName, group);
}
```
...to...
```
if (!isEmberArray(group)) {
group = emberArray();
groups[`${groupName}`] = group;
}
```
...will fix the problem and …
=> Allow group-by with strings that contain punctuation

README.md, UPGRADING.md
I recently was upgrading a project from 1.x to 2.x and resorted to the commit history to understand the reason the major version was bumped. This PR adds a simple doc for folks to see what changed.
[rendered](https://github.com/blimmer/ember-composable-helpers/blob/790f9900e2a3c7f7e79032e00994f56ac2188092/UPGRADING.md)
=> Add an upgrade guide from 1.x to 2.x

blueprints/ember-composable-helpers/index.js
Check first to see if ember-cli-shims is installed as a package (which
it is after ember-cli 2.11.
Closes #254 
Some caveats:
1) This is the only idea I had for preventing an unnecessary bower install. It might be a bad one.
2) I don't have any knowledge of the `options` parameter I used to detect the installation of `ember-cli-shims` - passing it in is part of the API docs at https://ember-cli.com/api/classes/Blueprint.html but there are no details.
3) I don't think there is a way to test the blueprint.
=> Only install ember-cli-shims if it doesn't exist

index.js
The PR makes ember-composable-helpers read its options from either `this.parent` or `this.app`.
The "issue" is that relying only on `this.app` makes it impossible to configure from within an engine.
The changed code is copied from [`ember-cli-babel`](https://github.com/babel/ember-cli-babel/blob/master/index.js#L137).
=> Read options from parent or app

app/helpers/compact.js, app/helpers/drop.js, app/helpers/filter-by.js, app/helpers/filter.js, app/helpers/find-by.js, app/helpers/group-by.js, app/helpers/intersect.js, app/helpers/join.js, app/helpers/map-by.js, app/helpers/map.js, app/helpers/reduce.js, app/helpers/reject-by.js, app/helpers/reverse.js, app/helpers/slice.js, app/helpers/sort-by.js, app/helpers/take.js, app/helpers/union.js
These things are all reexports of names that don't actually exist. If anybody tries to use these, they get an error. But almost certainly nobody tries to use these, because they shouldn't anyway. They should import the originals directly out of the addon's namespace, not the app's namespace.
I noticed this issue because I'm experimenting with more automatic dependency traversal, and these bad links generate warnings.
=> Remove reexports of nonexistent names

blueprints/ember-composable-helpers/index.js
Closes #303
Removes blueprint that adds `ember-cli-shims` to the bower.json
=> Adding ember-cli-shims to bower is not longer needed nor advised.

addon/helpers/without.js, tests/integration/helpers/without-test.js
Closes #268.
Ember Data collections return `instance` when run through `Ember.typeOf`. This PR changes the array check of `needle` to use `isEmberArray`, which also detects Ember Data collections.
=> Updating without helper to work with ember data arrays. Fixes #268.

index.js, lib/strip-bad-reexports.js, package.json, yarn.lock
This fixes #308.
As there is no existing test infrastructure for running builds with different build-time options, there was not a good place to put a test so I didn't make one.
The changes here fix both parts of the problem reported in #308.
- in the addon tree, we need to rewrite the `index.js` file so it stops trying to import helpers that have already been removed.
- in the app tree, we need to remove the files that reexport removed helpers.
=> fix unused helper stripping

addon/helpers/take.js, tests/integration/helpers/take-test.js
This avoids `Cannot read property 'slice' of null` when you use `{{take}}` with a null array.
=> allow `{{take}}` to be used with null arrays

package.json, tests/unit/helpers/chunk-test.js, yarn.lock
extracted from https://github.com/DockYard/ember-composable-helpers/pull/321
This has a single failure for `Unit | Helper | chunk: it handles arrays with computed property lengths`:
It seems that this fails in 3.13:
```js
let ap = emberArrayProxy.extend({
content: emberArray([1, 2, 3]),
length: computed('content.[]', function() {
return this.get('content.length');
})
}).create();
```
=> Upgrade to Ember 3.13

addon/helpers/map-by.js, tests/integration/helpers/map-by-test.js
This avoids "array is null" when you use {{map-by}} with a null array.
This was broken by #323 when it was updated to `map` on the array directly instead of using the Ember computed `mapBy`.
=> Handle null array in map-by

README.md
Fixes missing `install` command for legacy install instructions.
=> Fix install instructions on Ember 3.12 and below

addon/helpers/slice.js, tests/integration/helpers/slice-test.js
Adds support for 2-argument slice call: `{{slice 1 array}}`.
I saw #259, but it seems it was abandoned, so I created new PR.
=> allow 2 args {{slice}}

README.md, addon/helpers/entries.js, addon/helpers/keys.js, app/helpers/entries.js, app/helpers/keys.js, tests/integration/helpers/entries-test.js, tests/integration/helpers/keys-test.js
Closes # [351](https://github.com/DockYard/ember-composable-helpers/issues/351)
This PR adds new `keys` & `entries` helpers to work with object.
=> [Feature] Object keys & entries helpers 

README.md, addon/helpers/from-entries.js, addon/helpers/values.js, app/helpers/from-entries.js, app/helpers/values.js, tests/integration/helpers/from-entries-test.js, tests/integration/helpers/values-test.js
Closes (the second half of) #351 .
This PR adds `values` and `from-entries` Object helpers, to complement the `keys` and `entries` helpers added in #335 
See details in #351
=> Object helpers

README.md, addon/helpers/pick.js, app/helpers/pick.js, tests/integration/helpers/pick-test.js
Hello! Long time listener, first time caller....
This PR introduces a `pick` helper. When using the {{on}} modifier, I've found myself writing a lot of component actions that grab a particular value off of the emitted event to pass along. This helper makes it easy to pick off a particular value and either return it or send it to an optional action. 
I was considering creating an addon for this, but it fits well within the composable helpers domain, so I figured I'd propose it here first. 
I'm open to suggestions on improvements
=> Pick Helper

addon/helpers/sort-by.js, tests/integration/helpers/filter-test.js, tests/integration/helpers/map-by-test.js, tests/integration/helpers/sort-by-test.js
The refactor of `sort-by` in #362 by @snewcomer no longer accepts a resolved Ember Data hasMany relationship as [this line](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/sort-by.js#L28) throws `array is not iterable`.
=> Fix sort-by to accept Ember Data relationship

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
Native JS sort sorts by ASCII code, from lowest to highest.
'a'.charCodeAt() === '97'
'A'.charCodeAt() === '65'
```
// native JS
['a', 'A', 'b'].sort() === ['A', 'a', 'b']
```
```
// This PR
['a', 'A', 'b'].sort() === ['A', 'a', 'b']
```
However, the human mind may prefer `['a', 'A', 'b']` (subjective).  The best way to think about it as case insensitive ordering.
Follow up - AlphaNumeric ordering. (skipped test)
close #369
=> Refactor sort by to Alphabetical instead of ASCII(betical)

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
Before #370 `undefined` values could be sorted, now they can again.
=> Ignore undefined values when sorting

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
=> Further improve sorting algorithm to put undefined values at end of list

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
https://github.com/DockYard/ember-composable-helpers/pull/376/commits/e7a8f01a2d84545924e6919d50ef1c19397b669d breaks `sort-by` when a value is `null` since `null.toLowerCase` throws the following:
```
Uncaught TypeError: Cannot read property 'toLowerCase' of null
```
I suppose the truthy checks were required after all to prevent that
---
I'm not sure what the ideal handling of null values should be, so this PR is just my take:
I believe null values should be sorted last as well since doing comparisons to null can lead to inconsistent sorting:
```js
// Ignored (left in place) when compared to strings
"a" < null // false
"a" > null // false
// Sorted when compared to numbers
1 > null // true
1 < null // false
```
However, this doesn't sort between `undefined` and `null` -- not sure if …
=> Fix sort-by with null values

addon/helpers/contains.js, addon/helpers/includes.js, addon/helpers/without.js, addon/utils/includes.js, app/helpers/includes.js, tests/integration/helpers/includes-test.js
This renamed `{{contains}}` helper to `{{includes}}` as discussed in #365. A deprecation warning is added for the old name.
Additional I have refactored to code:
- Remove code only needed to support Ember versions, which fall back to `EmberArray.contains()` if `EmberArray.includes()` is not available. `EmberArray.contains()` has been removed in 2.x. `EmberArray.includes()` is available in all supported version.
- Avoid converting the array passed in multiple times to `EmberArray` if an array of needles is provided.
- Use `Array.every()` (or `EmberArray.every()`) instead of `Array.reduce()` to improve readability and performance.
- Use same code path for single needle and array of needles to reduce complexity. This may have a bad performance impact as it requires creating an interim array …
=> Rename {{contains}} helper to {{includes}}

addon/helpers/intersect.js, tests/integration/helpers/intersect-test.js
I am attempting to upgrade from `ember-composable-helpers` from 2.x.x to 4.x.x  and I am seeing an issue when using `intersect` with 2 parameters, the first initially being `null` due to a promise.
The stack trace thrown was:
```
TypeError: Cannot read property 'length' of null
at http://localhost:7357/assets/vendor.js:90243:35
at Array.filter (<anonymous>)
at intersect (http://localhost:7357/assets/vendor.js:90238:41)
at http://localhost:7357/assets/vendor.js:5829:29
at deprecateMutationsInAutotrackingTransaction (http://localhost:7357/assets/vendor.js:55142:9)
at EmberHelperRootReference.fnWrapper [as fn] (http://localhost:7357/assets/vendor.js:5828:70)
at http://localhost:7357/assets/vendor.js:47086:34
at runInAutotrackingTransaction (http://localhost:7357/assets/vendor.js:55114:9)
at …
```
=> use `confirmedArrays` when performing intersect

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
Closes #387
added check for null or undefined, before ember's get usage to prevent mentioned errors
=> [sort-by] Cannot call get with [keyName] on an undefined object.

addon/helpers/sort-by.js, tests/integration/helpers/sort-by-test.js
Fixed case where some sorting values are null and other sorting keys doesn't applied
=> fixes sort-by case with multiple properties and nulls

README.md
👋 Let me know if anything needs updating.
=> Document "includes" helper
